server:
  port: 9002

spring:
  application:
    name: biz-service
  config:
    use-legacy-processing: true
  profiles:
    active: local
  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    sql: debug
    web: debug
  file:
    name:
      path: /logs

log:
  config:
    path: file:D:/workspace/skinnovation/BizService/log

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: "skilcalife"

