server:
  port: 9002

spring:
  application:
    name: biz-service
  config:
    use-legacy-processing: true
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  mvc:
    log-request-details: true

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    sql: debug
#    web: debug
    org:
      springframework: debug
      springframework.web: debug

log:
  config:
    path: file:./log

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: "skilcalife"

