spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/tt_ski?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 741218g!$
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.90.2.203:1433;DatabaseName=SKI_LCA_WEB
    username: ENC(02TJayD6q3sklfgIob+ws+rPyNlQTlrZ)
    password: ENC(mw4qTfR1fmLUq6AId+r8qXWIiVh+JkVD)
