spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;selectMethod=cursor;instanceName=SKI_LCA_WEB;integratedSecurity=true
    username: sa
    password: qwer1234!$
